version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: /public/beforeinstall.sh
  ApplicationStart:
    - location: /public/applicationstart.sh
