version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: public/beforeinstall.sh
      timeout: 300
  ApplicationStart:
    - location: public/applicationstart.sh
      timeout: 300
